#!/usr/bin/env python3
"""
Project Tree Generator → Saves to PROJECT_STRUCTURE.md

Scans the current directory recursively and writes a clean,
ASCII-style tree structure to PROJECT_STRUCTURE.md,
excluding virtual environments and other dev artifacts.
"""

import os
from pathlib import Path

# Folders to exclude (case-insensitive)
EXCLUDE_DIRS = {
    '.venv', 'venv', 'env', '.env', '__pycache__', '.git', '.idea',
    '.vscode', 'node_modules', '.mypy_cache', '.pytest_cache', 'build',
    'dist', '.eggs', '.tox'
}

def should_exclude(path: Path) -> bool:
    """Check if a path should be excluded from the tree."""
    name = path.name
    # Exact matches (case-insensitive)
    if name.lower() in {d.lower() for d in EXCLUDE_DIRS if not d.endswith('*')}:
        return True
    # Handle common patterns
    if name.endswith(('.egg-info', '.dist-info')):
        return True
    return False

def get_tree_lines(root: Path, prefix: str = "", is_last: bool = True) -> list:
    """Recursively generate lines for the tree structure."""
    lines = []
    try:
        items = sorted(
            [item for item in root.iterdir() if not should_exclude(item)],
            key=lambda x: (x.is_file(), x.name.lower())
        )
    except PermissionError:
        return [f"{prefix}└─ <PERMISSION DENIED>"]

    for i, item in enumerate(items):
        is_last_item = (i == len(items) - 1)
        connector = "└─ " if is_last_item else "├─ "

        if item.is_dir():
            lines.append(f"{prefix}{connector}{item.name}/")
            extension = "    " if is_last_item else "│   "
            lines.extend(get_tree_lines(item, prefix + extension, is_last_item))
        else:
            lines.append(f"{prefix}{connector}{item.name}")
    return lines

def main():
    root = Path.cwd()
    output_file = root / "PROJECT_STRUCTURE.md"

    # Build header
    content = [
        f"# Project Structure: `{root.name}`\n",
        "<!-- Generated by project_tree.py -->\n"
    ]

    # Generate tree
    content.append(f"{root.name}/")
    content.extend(get_tree_lines(root))

    # Write to file
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("\n".join(content))

    print(f"✅ Project structure saved to: {output_file}")
    print(f"📁 Scanned root: {root}")

if __name__ == "__main__":
    main()